export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_PRODUCTSS: "SET_PRODUCTSS",
    SET_CONTENT: "SET_CONTENT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
     ADD_TO_CART:"ADD_TO_CART",
       DELETE_PRODUCT_IN_CART:"DELETE_PRODUCT_IN_CART;",
         UPDATE_QUANTITY : "UPDATE_QUANTITY",
         FILTER : "FILTER",
         SET_FILTER_LOWER:" SET_FILTER_LOWER"
  };